### ISSUE TITLE
blank hash and array values are not allowed

### ISSUE THREAD

**Issue by smostovoy** [segment-integrations/integration-intercom#1]
Hey guys,
So what I have found - 
1. blank hash values
2. array values
lead to Intercom ignoring this event. It just doesn't appear in intercom at all. (In debugger, in keen.io and Calq it does appear)
Here is example (ruby):
```ruby
        traits = {
          user_id: 1,
          event: 'some event',
          properties: {
            bar: ['1'],
            foo: {}
          }
        }
Analytics.track(traits)
```
Just maybe worth to mention in your doc. It took me some time.

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
