### ISSUE TITLE
Add support for async/realtime messages in single page apps

### ISSUE THREAD

**Issue by swidnikk** [segment-integrations/integration-intercom#17]
See https://docs.intercom.io/install-on-your-web-product-or-site/integrating-intercom-in-a-single-page-app

for additional details. We're currently not seeing async messages reach users with this integration =/

**Comment by f2prateek** [comment]
Could you please write in to friends@segment.com as well? Someone from our success team will help you out!

**Comment by hankim813** [comment]
@swidnikk thanks for the note here. This belongs in the client side [Intercom repo](https://github.com/segment-integrations/analytics.js-integration-intercom). This is basically the same pain point surfaced in [this issue](https://github.com/segment-integrations/analytics.js-integration-intercom/issues/6) so will close this!
