### ISSUE TITLE
Unsubscribe does not seem to work

### ISSUE THREAD

**Issue by thewheat** [segment-integrations/integration-intercom#42]
Using the code from https://segment.com/docs/integrations/intercom/#unsubscribe-users as a template

- Ran the code below
- Did not update unsubscribe
- Did update `test_string` custom attribute

Am I missing anything here? 

```
analytics.identify({
  userId: '1',
  context:{
    Intercom: { unsubscribedFromEmails: true }
  },
  traits: {
    test_string: 'test string',
  }
});
```

**Comment by hankim813** [comment]
@thewheat hmm that should work. I've created a ticket internally for our engineers to repro this and update accordingly. Thanks for sharing!

**Comment by anoonan** [comment]
@thewheat this has been fixed! Feel free to follow up with any additional questions.
